version: '3.8'

services:
  # Servidor Web + PHP (API)
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: flutter_php_api
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./api/src:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=facul_db
      - DB_USER=flutter_user
      - DB_PASSWORD=flutter_password
    depends_on:
      - db
    networks:
      - app-network

  # Banco de Dados MySQL
  db:
    image: mysql:8.0
    container_name: flutter_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: facul_db
      MYSQL_USER: flutter_user
      MYSQL_PASSWORD: flutter_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # Gerenciador do Banco (Acessível em http://localhost:8080)
  adminer:
    image: adminer
    container_name: flutter_mysql_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge